apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
  - name: InfluxDB
    type: influxdb
    uid: InfluxDB
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    database: metrics
    user: telegraf
    secureJsonData:
      password: telegrafpass

