{
 "title": "Anomalies",
 "description": "detected anomalies from logs",
 "tags": [ "Anomalies-from-app-py" ],
 "time": { "from": "2026-03-26T22:00:00.000Z", "to": "2026-03-29T20:59:59.000Z" },
 "panels": [
  {
   "title": "All detected anomalies",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"anomalies-from-app-py\"} \r\n| json\r\n| line_format \"{{.detected_anomaly}} || {{.message}} || {{.atm_id}}\""
    }
   ]
  },
  {
   "title": "A1: Network Timeout Cascade",
   "type": "logs",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"anomalies-from-app-py\", anomaly_type=\"A1: Network Timeout Cascade\"} |= ``"
    }
   ]
  },
  {
   "title": "A2: Cash Cassettes Empty",
   "type": "logs",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"anomalies-from-app-py\", anomaly_type=\"A2: Cash Cassettes Empty\"} |= ``"
    }
   ]
  },
  {
   "title": "A4: Container Restart Loop",
   "type": "logs",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"anomalies-from-app-py\", anomaly_type=\"A4: Container Restart Loop\"} |= ``"
    }
   ]
  },
  {
   "title": "A5: High Response Time Spike + Success Rate Drop",
   "type": "logs",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"anomalies-from-app-py\", anomaly_type=\"A5: High Response Time Spike + Success Rate Drop\"} |= ``"
    }
   ]
  },
  {
   "title": "A7: Malformed Prometheus record",
   "type": "logs",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"anomalies-from-app-py\", anomaly_type=\"A7: Malformed Prometheus record\"} |= ``"
    }
   ]
  },
  {
   "title": "A7: Schema validation failure",
   "type": "logs",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"anomalies-from-app-py\", anomaly_type=\"A7: Schema validation failure\"} |= ``"
    }
   ]
  }
 ]
}